[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.install]
cmds = ["npm install --omit=optional"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "chromium"
